export enum ErrorCode {
  DB_INIT_FAILED = 'DB_INIT_FAILED',
  MIGRATION_FAILED = 'MIGRATION_FAILED',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_INVALID_INPUT = 'PROJECT_INVALID_INPUT',
  PROJECT_PATH_NOT_FOUND = 'PROJECT_PATH_NOT_FOUND',
  PROJECT_PATH_DUPLICATE = 'PROJECT_PATH_DUPLICATE',
  WORK_ITEM_NOT_FOUND = 'WORK_ITEM_NOT_FOUND',
  DECISION_NOT_FOUND = 'DECISION_NOT_FOUND',
  DEPENDENCY_CYCLE = 'DEPENDENCY_CYCLE',
  DEPENDENCY_DUPLICATE = 'DEPENDENCY_DUPLICATE',
  DEPENDENCY_SELF = 'DEPENDENCY_SELF',
  HANDOFF_NOT_FOUND = 'HANDOFF_NOT_FOUND',
  HANDOFF_INVALID_TRANSITION = 'HANDOFF_INVALID_TRANSITION',
  NOT_INITIALIZED = 'NOT_INITIALIZED',
}

export class EndeavorError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'EndeavorError';
  }
}
